# Generated by Django 2.2.7 on 2019-11-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0004_auto_20191114_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzamenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_toppings', models.IntegerField()),
                ('price', models.IntegerField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Base_menu', to='pizzaapp.Base')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Size_menu', to='pizzaapp.Size')),
            ],
        ),
    ]
