# Generated by Django 2.2.7 on 2019-11-15 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizzaapp', '0005_pizzamenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamenu',
            name='price',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Shop_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_pizza', models.ManyToManyField(blank=True, related_name='items_pizza', to='pizzaapp.Pizza')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
