# Generated by Django 2.2.7 on 2019-11-20 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizzaapp', '0006_auto_20191115_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ManyToManyField(blank=True, related_name='orders', to='pizzaapp.Shop_cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
