# Generated by Django 2.2.7 on 2019-11-20 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0012_auto_20191120_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracheese', models.BooleanField(blank=True)),
                ('price', models.IntegerField()),
                ('base', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Base', to='pizzaapp.Base')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_toppings', models.IntegerField()),
                ('price', models.FloatField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Base_menu', to='pizzaapp.Base')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizzamenu',
            name='base',
        ),
        migrations.RemoveField(
            model_name='pizzamenu',
            name='size',
        ),
        migrations.RemoveField(
            model_name='shop_cart',
            name='items_pizza',
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='pizzaapp.Item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserOrder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Pizzamenu',
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Name_menu', to='pizzaapp.Name'),
        ),
        migrations.AddField(
            model_name='menu',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Size_menu', to='pizzaapp.Size'),
        ),
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Type_menu', to='pizzaapp.Type'),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Name', to='pizzaapp.Name'),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Size', to='pizzaapp.Size'),
        ),
        migrations.AddField(
            model_name='item',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='Toppings', to='pizzaapp.Toppings'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Type', to='pizzaapp.Type'),
        ),
        migrations.AddField(
            model_name='shop_cart',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='ItemsPizza', to='pizzaapp.Item'),
        ),
    ]
