# Generated by Django 2.2.7 on 2019-11-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0013_auto_20191120_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='base',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='base',
        ),
        migrations.DeleteModel(
            name='Base',
        ),
    ]
