# Generated by Django 2.2.7 on 2019-11-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0015_menu_extracheese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='no_toppings',
            field=models.IntegerField(blank=True),
        ),
    ]
