# Generated by Django 2.2.7 on 2019-11-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0018_auto_20191120_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='no_toppings',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
