# Generated by Django 2.2.7 on 2019-11-20 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0020_auto_20191120_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='price',
            new_name='baseprice',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Size', to='pizzaapp.Size'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='no_toppings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
