# Generated by Django 2.2.7 on 2019-11-21 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0022_auto_20191120_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typename', to='pizzaapp.Type'),
        ),
    ]
