# Generated by Django 2.2.7 on 2019-11-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0023_name_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typetopping', to='pizzaapp.Type'),
        ),
    ]
