# Generated by Django 2.2.7 on 2019-11-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0024_toppings_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='extracheese',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
