# Generated by Django 2.2.7 on 2019-11-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0025_auto_20191122_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
