# Generated by Django 2.2.7 on 2019-11-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0029_auto_20191126_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop_cart',
            name='totalprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
