# Generated by Django 2.2.7 on 2019-11-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0031_auto_20191127_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
