# Generated by Django 2.2.7 on 2019-11-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0033_auto_20191127_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
    ]
